			<!-- ============================================================== -->
			<!-- Start Content here -->
			<!-- ============================================================== -->
            <div class="content">
								<!-- Page Heading Start -->
				<div class="page-heading">
            		<h1><i class='icon-doc-new'></i> Cadastrar Funcionário</h1>
            		<h3>Funcionários > Cadastrar Funcionário</h3>            	</div>
            	<!-- Page Heading End-->				
				<div class="row">
					<div class="col-md-12 portlets">
						<!-- Your awesome content goes here -->
						<div class="widget animated fadeInDown">
								<form id="myWizard">
								<section class="step" data-step-title="Informações Pessoais">
									<div class="row">
										<div class="col-sm-6">
											<div class="form-group">
												<label for="nome">Nome</label>
												<input type="text" id="nome" name="nome" placeholder="Nome" class="form-control">
											</div>
											<div class="form-group">
												<label for="idade">Idade</label>
												<input type="text" id="idade" name="idade" placeholder="Idade" class="form-control">
											</div>
											<div class="form-group">
												<label for="cep">CEP</label>
												<input type="text" id="cep" name="cep" placeholder="CEP" class="form-control">
											</div>
											<div class="form-group">
												<label for="end">Endereço</label>
												<input type="text" id="end" name="end" placeholder="Endereço" class="form-control">
											</div>
										
											
										</div>
										<div class="col-sm-6">
											<div class="form-group">
												<label for="bairro">Bairro</label>
												<input type="text" id="bairro" name="bairro" placeholder="Bairro" class="form-control">
											</div>
											<div class="form-group">
												<label for="codade">Cidade</label>
												<input type="text" id="cidade" name="cidade" placeholder="Cidade" class="form-control">
											</div>
											<div class="form-group">
												<label for="uf">UF</label>
												<input type="text" id="uf" name="uf" placeholder="UF" class="form-control">
											</div>
											<div class="form-group">
												<label for="sexo">Sexo</label>
												<select id="sexo" name="sexo" class="form-control">
												    <option value="Masculino">Masculino</option>
												    <option value="Feminino">Feminino</option>
												</select>
											</div>
										</div>
									</div>
								</section>
								<section class="step" data-step-title="Informações Profissionais">
									<div class="row">
										<div class="col-sm-6">
											<div class="form-group">
												<label for="departamento">Departamento</label>
												<select id="departamento" name="departamento" class="form-control">
												    <option value="Fiscal">Fiscal</option>
												    <option value="Contábil">Contábil</option>
												    <option value="Financeiro">Financeiro</option>
												    <option value="Recursos Humanos">Recursos Humanos</option>
												</select>
											</div>
											<div class="form-group">
												<label for="cargo">Cargo</label>
												<input type="text" id="cargo" name="cargo" placeholder="Cargo" class="form-control">
											</div>
											<div class="form-group">
												<label for="salario">Salário</label>
												<input type="text" id="salario" name="salario" placeholder="Salário" class="form-control">
											</div>
											<div class="form-group">
												<label for="custoTotal">Custo Total</label>
												<input type="text" id="custoTotal" name="custoTotal" placeholder="Custo Total" class="form-control">
											</div>
										</div>
									</div>
								</section>
								<section class="step" data-step-title="Informações de Login">
									<div class="row">
										<div class="col-sm-6">
											<div class="form-group">
												<label for="usuario">Usuário</label>
												<input type="text" id="usuario" name="usuario" placeholder="Usuário" class="form-control">
											</div>
											<div class="form-group">
												<label for="senha">Senha</label>
												<input type="password" id="senha" name="senha" placeholder="Senha" class="form-control">
											</div>
											<div class="form-group">
												<label for="confirmarSenha">Confirmar Senha</label>
												<input type="password" id="confirmarSenha" name="confirmarSenha" placeholder="Confirmar Senha" class="form-control">
											</div>
											<div class="form-group">
												<label for="email">E-mail</label>
												<input type="text" id="email" name="email" placeholder="E-mail" class="form-control">
											</div>
										</div>
									</div>
								</section>
							</form>
						</div>
					</div>
				</div>
				            <!-- Footer Start -->
            <!-- Footer End -->			
            </div>
			<!-- ============================================================== -->
			<!-- End content here -->
			<!-- ============================================================== -->

	        