			<!-- ============================================================== -->
			<!-- Start Content here -->
			<!-- ============================================================== -->
            <div class="content">
								<!-- Page Heading Start -->
				<div class="page-heading">
            		<h1><i class='icon-doc-new'></i> Editar Departamento</h1>
            		<h3>Departamentos > Editar Departamento</h3>            	</div>
            	<!-- Page Heading End-->				
				<div class="row">
					<div class="col-md-12 portlets">
						<!-- Your awesome content goes here -->
						<div class="widget">
							<div class="widget-header transparent">
								<h2><strong>Editar de Departamento</strong></h2>
								<div class="additional-btn">
									<a href="#" class="widget-toggle"><i class="icon-down-open-2"></i></a>
								</div>
							</div>
							<div class="widget-content padding">							
								<div id="basic-form">
									<form role="form" method="post" action="<?= $this->basePath()?>/departamento/editar/<?= $departamento->getId() ?>">
									  <div class="form-group">
										<label for="departamento">Nome</label>
										<input type="hidden" name="id_departamento" value="<?= $departamento->getId() ?>" />
										<input type="text" class="form-control" value="<?= $departamento->getNome() ?>" id="departamento" name="nome" placeholder="Nome do Departamento" />
									  </div>
									  <input type="submit" class="btn btn-default" value="Editar" />
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
				            <!-- Footer Start -->
            <!-- Footer End -->			
            </div>
			<!-- ============================================================== -->
			<!-- End content here -->
			<!-- ============================================================== -->

	        