<div class="container-fluid">
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">

            </h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i>  <a href="javascript:void(0)">Dashboard</a>
                </li>
                <li class="active">
                    <i class="fa fa-edit"></i> Cadastro de Empresas
                </li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <h1 class="text-center">Cadastro de Empresas</h1>

            <form role="form" id="emp-cad-form" method="post" enctype="multipart/form-data" action="<?php echo $this->basePath()?>/cadastrar">
                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3">
                        <fieldset class="fieldset-empresa">
                            <div class="form-group">
                                <label class="control-label" for="razao-social">Razão Social</label>
                                <input type="text" class="form-control obr" id="razao-social" name="razao-social">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="nome-fantasia">Nome Fantasia</label>
                                <input type="text" class="form-control obr" id="nome-fantasia" name="nome-fantasia">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="cnpj">CNPJ</label>
                                <input type="text" class="form-control obr" id="cnpj" name="cnpj">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="inscricao-estadual">Inscrição Estadual</label>
                                <input type="text" class="form-control obr" id="inscricao-estadual" name="inscricao-estadual">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="inscricao-municipal">Inscrição Municipal</label>
                                <input type="text" class="form-control obr" id="inscricao-municipal" name="inscricao-municipal">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="cnae-principal">CNAE Principal</label>
                                <input type="text" class="form-control obr" id="cnae-principal" name="cnae-principal">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="cnae-secundario">CNAE Secundário</label>
                                <input type="text" class="form-control obr" id="cnae-secundario" name="cnae-secundario">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="regime-tributacao">Regime de Tributação</label>
                                <input type="text" class="form-control obr" id="regime-tributacao" name="regime-tributacao">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="valor-honorarios">Valor dos Honorários</label>
                                <input type="text" class="form-control obr" id="valor-honorarios" name="valor-honorarios">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="vencimento-honorarios">Vencimento dos Honorários</label>
                                <input type="text" class="form-control obr datepicker" id="vencimento-honorarios" name="vencimento-honorarios">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="vencimento-procuracao-caixa">Vencimento da Procuração Caixa</label>
                                <input type="text" class="form-control datepicker" id="vencimento-procuracao-caixa" name="vencimento-procuracao-caixa">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="vencimento-procuracao-rfb">Vencimento da Procuração RFB</label>
                                <input type="text" class="form-control datepicker" id="vencimento-procuracao-rfb" name="vencimento-procuracao-rfb">
                            </div>

                            <div class="form-group">
                                <label for="certificado-digital">Certificado Digital</label>
                                <input type="file" id="certificado-digital" name="certificado-digital">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="senha-web">Senha da Web</label>
                                <input type="text" class="form-control" id="senha-web" name="senha-web">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="senha-fazenda">Senha da Fazenda</label>
                                <input type="text" class="form-control" id="senha-fazenda" name="senha-fazenda">
                            </div>

                            <div class="form-group">
                                <label for="tipo-empresa">Tipo da Empresa</label>
                                <select class="form-control" id="tipo-empresa" name="tipo-empresa">
                                    <option value="">Escolha</option>
                                <?php foreach($combos['tipo-empresa'] as $chave => $tipo): ?>
                                    <option value="<?=$chave?>"><?=$tipo?></option>
                                <?php endforeach;  ?>    
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="contrato">Contrato</label>
                                <input type="file" id="contrato" name="contrato">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="vencimento-contrato">Vencimento do Contrato</label>
                                <input type="text" class="form-control datepicker" id="vencimento-contrato" name="vencimento-contrato">
                            </div>
                        </fieldset>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3">
                        <fieldset class="fieldset-endereco">
                            <div class="form-group">
                                <label class="control-label" for="logradouro">Logradouro</label>
                                <input type="text" class="form-control obr" id="logradouro" name="logradouro">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="numero">Número</label>
                                <input type="text" class="form-control obr" id="numero" name="numero">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="complemento">Complemento</label>
                                <input type="text" class="form-control" id="complemento" name="complemento">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="bairro">Bairro</label>
                                <input type="text" class="form-control obr" id="bairro" name="bairro">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="municipio">Município</label>
                                <input type="text" class="form-control obr" id="municipio" name="municipio">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="cep">CEP</label>
                                <input type="text" class="form-control obr cep" id="cep" name="cep">
                            </div>

                            <div class="form-group">
                                <label for="estado">Estado</label>
                                <select class="form-control obr" id="estado" name="estado">
                                    <option value="">Escolha</option>
                                <?php foreach($combos['estados'] as $sigla => $estado): ?>
                                    <option value="<?=$sigla?>"><?=$estado?></option>
                                <?php endforeach;  ?>
                                </select>
                            </div>
                        </fieldset>
                    </div>
                </div>


                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3">
                        <fieldset class="fieldset-usuario">
                            <div class="form-group">
                                <label class="control-label" for="email">Email</label>
                                <input type="text" class="form-control obr email" id="email" name="email">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="login">Login</label>
                                <input type="text" class="form-control obr login" id="login" name="login">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="senha">Senha</label>
                                <input type="password" class="form-control obr senha" id="senha" name="senha">
                            </div>
                        </fieldset>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary emp-cad">Cadastrar</button>
            </form>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
            </h1>
        </div>
    </div>
</div>