<div class="container-fluid">

                <!-- Modal -->
        <div class="container">
          <div class="modal fade" id="detalhe" role="dialog">
              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-body" style="padding:40px 50px;">
                    
                    <div class="row">
                        <div class="col-lg-3 col-lg-offset-1">
                            Nome:
                        </div>
                        <div class="col-lg-5 col-lg-offset-6">
                            Jurandir Dacol Junior
                        </div>
                    </div> 
                    <div class="row">
                        <div class="col-lg-3 col-lg-offset-1">
                            Nome:
                        </div>
                        <div class="col-lg-5 col-lg-offset-6">
                            Jurandir Dacol Junior
                        </div>
                    </div> 
                    <div class="row">
                        <div class="col-lg-3 col-lg-offset-1">
                            Nome:
                        </div>
                        <div class="col-lg-5 col-lg-offset-6">
                            Jurandir Dacol Junior
                        </div>
                    </div> 
                    <div class="row">
                        <div class="col-lg-3 col-lg-offset-1">
                            Nome:
                        </div>
                        <div class="col-lg-5 col-lg-offset-6">
                            Jurandir Dacol Junior
                        </div>
                    </div> 
                    
                </div>
            </div>
          </div> 
        </div>
          <!-- Modal -->
</div>

<script>$(function(){$('#detalhe').modal('show');});</script>