<div class="container-fluid">
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">

            </h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i>  <a href="javascript:void(0)">Dashboard</a>
                </li>
                <li class="active">
                    <i class="fa fa-edit"></i> Edição de Empresas
                </li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <h1 class="text-center">Cadastro de Empresas</h1>

            <form role="form" id="emp-cad-form" enctype="multipart/form-data" method="post" action="<?php echo $this->basePath()?>/empresa/editar/<?= $empresa['id'] ?>">
                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3">
                        <fieldset class="fieldset-empresa">
                            <input type="hidden" name="id" value="<?= $id ?>">
                            <input type="hidden" name="end_id" value="<?= $empresa['end_id'] ?>">
                            <input type="hidden" name="usr_id" value="<?= $empresa['usr_id'] ?>">
                            <input type="hidden" name="status" value="<?= $empresa['status'] ?>">
                            <div class="form-group">
                                <label class="control-label" for="razao-social"> * Razão Social</label>
                                <input type="text" class="form-control obr" id="razao-social" name="razao-social" value="<?= $empresa['razao_social'] ?>">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="nome-fantasia"> * Nome Fantasia</label>
                                <input type="text" class="form-control obr" id="nome-fantasia" name="nome-fantasia" value="<?= $empresa['nome_fantasia'] ?>">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="cnpj"> * CNPJ</label>
                                <input type="text" class="form-control cnpj obr" id="cnpj" name="cnpj" value="<?= $empresa['cnpj'] ?>">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="inscricao-estadual"> * Inscrição Estadual</label>
                                <input type="text" class="form-control obr" id="inscricao-estadual" name="inscricao-estadual" value="<?= $empresa['inscricao_estadual'] ?>">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="inscricao-municipal"> * Inscrição Municipal</label>
                                <input type="text" class="form-control obr" id="inscricao-municipal" name="inscricao-municipal" value="<?= $empresa['inscricao_municipal'] ?>">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="cnae-principal"> * CNAE Principal</label>
                                <input type="text" class="form-control obr" id="cnae-principal" name="cnae-principal" value="<?= $empresa['CNAE_principal'] ?>">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="cnae-secundario">CNAE Secundário</label>
                                <input type="text" class="form-control obr" id="cnae-secundario" name="cnae-secundario" value="<?= $empresa['CNAE_secundario'] ?>">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="regime-tributacao">Regime de Tributação</label>
                                <input type="text" class="form-control obr" id="regime-tributacao" name="regime-tributacao" value="<?= $empresa['regime_tributacao'] ?>">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="valor-honorarios">Valor dos Honorários</label>
                                <input type="text" class="form-control obr" id="valor-honorarios" name="valor-honorarios" value="<?= Application\Utils\Money::toCurrency($empresa['valor_honorarios']) ?>">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="vencimento-honorarios">Vencimento dos Honorários</label>
                                <input type="text" class="form-control obr datepicker" id="vencimento-honorarios" name="vencimento-honorarios" value="<?= Application\Utils\DateConversion::conversion($empresa['vencimento_honorarios']) ?>">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="vencimento-procuracao-caixa">Vencimento da Procuração Caixa</label>
                                <input type="text" class="form-control datepicker" id="vencimento-procuracao-caixa" name="vencimento-procuracao-caixa" value="<?= Application\Utils\DateConversion::conversion($empresa['vencimento_procuracao_caixa']) ?>">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="vencimento-procuracao-rfb">Vencimento da Procuração RFB</label>
                                <input type="text" class="form-control datepicker" id="vencimento-procuracao-rfb" name="vencimento-procuracao-rfb" value="<?= Application\Utils\DateConversion::conversion($empresa['vencimento_procuracao_RFB']) ?>">
                            </div>

                            <div class="form-group">
                                <label for="certificado-digital" class="btn btn-primary">Upload de Certificado Digital</label><br /><span class="certificado-digital"><?php echo $empresa['certificado_digital'] ? substr($empresa['certificado_digital'],6) : 'Nenhum arquivo selecionado' ?></span>
                                <input type="file" id="certificado-digital" name="certificado-digital">
                                <input type="hidden" name="certificado-digital" value="<?= $empresa['certificado_digital'] ?>">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="senha-web">Senha da Web</label>
                                <input type="text" class="form-control" id="senha-web" name="senha-web" value="<?= $empresa['senha_web'] ?>">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="senha-fazenda">Senha da Fazenda</label>
                                <input type="text" class="form-control" id="senha-fazenda" name="senha-fazenda" value="<?= $empresa['senha_fazenda'] ?>">
                            </div>

                            <div class="form-group">
                                <label for="tipo-empresa">Tipo da Empresa</label>
                                <select class="form-control" id="tipo-empresa" name="tipo-empresa">
                                    <option value="">Escolha</option>
                                <?php foreach(Application\Model\Rotulos::$tipoEmpresa as $chave => $tipo): ?>
                                    <option value="<?=$chave?>" <?php if($empresa['tipo_empresa'] == $chave) echo 'selected="selected"'?>><?=$tipo?></option>
                                <?php endforeach;  ?>    
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="contrato" class="btn btn-primary">Upload de Contrato</label><br /><span class="contrato"><?php echo $empresa['contrato'] ? substr($empresa['contrato'],6) : 'Nenhum arquivo selecionado' ?></span>
                                <input type="file" id="contrato" name="contrato">
                                <input type="hidden" name="contrato" value="<?= $empresa['contrato'] ?>">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="vencimento-contrato">Vencimento do Contrato</label>
                                <input type="text" class="form-control datepicker" id="vencimento-contrato" name="vencimento-contrato" value="<?= Application\Utils\DateConversion::conversion($empresa['vencimento_contrato']) ?>">
                            </div>
                        </fieldset>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3">
                        <fieldset class="fieldset-endereco">
                            <div class="form-group">
                                <label class="control-label" for="logradouro">Logradouro</label>
                                <input type="text" class="form-control obr" id="logradouro" name="logradouro" value="<?= $empresa['logradouro'] ?>">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="numero">Número</label>
                                <input type="text" class="form-control obr" id="numero" name="numero" value="<?= $empresa['numero'] ?>">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="complemento">Complemento</label>
                                <input type="text" class="form-control" id="complemento" name="complemento" value="<?= $empresa['complemento'] ?>">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="bairro">Bairro</label>
                                <input type="text" class="form-control obr" id="bairro" name="bairro" value="<?= $empresa['bairro'] ?>">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="municipio">Município</label>
                                <input type="text" class="form-control obr" id="municipio" name="municipio" value="<?= $empresa['municipio'] ?>">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="cep">CEP</label>
                                <input type="text" class="form-control obr cep" id="cep" name="cep" value="<?= $empresa['cep'] ?>">
                            </div>

                            <div class="form-group">
                                <label for="estado">Estado</label>
                                <select class="form-control obr" id="estado" name="estado">
                                    <option value="">Escolha</option>
                                <?php foreach(Application\Model\Rotulos::$UF as $sigla => $estado): ?>
                                    <option value="<?=$sigla?>"  <?php if($empresa['estado'] == $sigla) echo 'selected="selected"'?>><?=$estado?></option>
                                <?php endforeach;  ?>
                                </select>
                            </div>
                        </fieldset>
                    </div>
                </div>


                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3">
                        <fieldset class="fieldset-usuario">
                            <div class="form-group">
                                <label class="control-label" for="email">Email</label>
                                <input type="text" class="form-control obr email" id="email" name="email" value="<?= $empresa['email'] ?>">
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="login">Login</label>
                                <input type="text" class="form-control obr login" id="login" name="login" value="<?= $empresa['login'] ?>">
                            </div>
                        </fieldset>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary emp-cad">Editar</button>
            </form>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">

            </h1>
        </div>
    </div>
</div>