<div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">

                        </h1>
                        <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard"></i>  <a href="javascript:void(0)">Dashboard</a>
                            </li>
                            <li class="active">
                                <i class="fa fa-table"></i> Listagem de Empresas
                            </li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->
<div class="container">
  <!-- Modal -->
  <div class="modal fade " id="confirm" role="dialog">
    <div class="modal-dialog"   style="top:200px;">
    
      <!-- Modal content-->
      <div class="modal-content">
          <div class="modal-body" style="padding:50px 20px;">
                Voce tem certeza que deseja excluir essa empresa?
          </div>
        <div class="modal-footer">
          <button class="btn btn-danger btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
          <button class="btn btn-success btn-default pull-right confirm-ok" data-dismiss="modal"><span class="glyphicon glyphicon-on"></span> Ok</button>
        </div>
      </div>     
    </div>
  </div> 
</div>

                <div class="row">
                    <div class="col-lg-12">
                        <h2>Listagem de Empresas</h2>
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr id="ordered">
                                        <th ord="desc" campo="id"><i class="fa fa-fw"></i> Id</th>
                                        <th ord="desc" campo="razao_social"><i class="fa fa-fw"></i> Razão Social</th>
                                        <th>CNPJ</th>
                                        <th>I.M.</th>
                                        <th>I.E.</th>
                                        <th>CNAE</th>
                                        <th ord="desc" campo="regime_tributacao"><i class="fa fa-fw"></i> Regime de Tributação</th>
                                        <th ord="desc" campo="valor_honorarios"><i class="fa fa-fw"></i> Valor dos Honorários</th>
                                        <th ord="desc" campo="vencimento_honorarios"><i class="fa fa-fw"></i> Vencimento dos Honorários</th>
                                        <th ord="desc" campo="status"><i class="fa fa-fw"></i> Status</th>
                                        <th>Editar</th>
                                        <th>Excluir</th>
                                        <th>Suspender</th>
                                    </tr>
                                </thead>
                                <tbody id="emp_content">
                                <?php
                                    if($empresas) {
                                        foreach($empresas as $empresa) {
                                          $status = $empresa['status'] == 'A' ? 'Ativa' : 'Inativa';  
                                ?>
                                    <tr>
                                        <td><?= $empresa['id'] ?></td>
                                        <td><?= $empresa['razao_social'] ?></td>
                                        <td><?= $empresa['cnpj'] ?></td>
                                        <td><?= $empresa['inscricao_municipal'] ?></td>
                                        <td><?= $empresa['inscricao_estadual'] ?></td>
                                        <td><?= $empresa['CNAE_principal'] ?></td>
                                        <td><?= $empresa['regime_tributacao'] ?></td>
                                        <td><?= $empresa['valor_honorarios'] ?></td>
                                        <td><?= Application\Utils\DateConversion::conversion($empresa['vencimento_honorarios']) ?></td>
                                        <td class="text-center status-emp-<?= $empresa['usr_id'] ?>"><?=$status ?></td>
                                        <td class="text-center"><a href="<?php echo $this->basePath()?>/editar/<?php echo $empresa['id'] ?>"><i class="fa fa-fw fa-edit"></i></a></td>
                                        <td class="text-center deletar"><a href="<?php echo $this->basePath()?>/deletar/<?php echo $empresa['id'] ?>"><i class="fa fa-fw fa-times"></i></a></td>
                                        <td class="suspender text-center" emp="<?= $empresa['usr_id'] ?>"><i class="fa fa-fw fa-lock"></i></td>
                                    </tr>
                                <?php
                                        }
                                    }
                                ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- /.row -->
                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                        </h1>
                    </div>
                </div>
                <!-- /.row -->

</div>