<div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">

                        </h1>
                        <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard"></i>  <a href="<?php echo $this->basePath()?>">Dashboard</a>
                            </li>
                            <li class="active">
                                <i class="fa fa-edit"></i> Cadastro de Empresas
                            </li>
                        </ol>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3">
                        <h1>Cadastro de Empresas</h1>

                        <form role="form" method="post" action="<?php echo $this->basePath()?>/application/empresa/cadastrar">
                            <fieldset class="fieldset-empresa">
                                <div class="form-group">
                                    <label class="control-label" for="razao-social">Razão Social</label>
                                    <input type="text" class="form-control" id="razao-social" name="razao-social">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="nome-fantasia">Nome Fantasia</label>
                                    <input type="text" class="form-control" id="nome-fantasia" name="nome-fantasia">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="cnpj">CNPJ</label>
                                    <input type="text" class="form-control" id="cnpj" name="cnpj">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="inscricao-estadual">Inscrição Estadual</label>
                                    <input type="text" class="form-control" id="inscricao-estadual" name="inscricao-estadual">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="inscricao-municipal">Inscrição Municipal</label>
                                    <input type="text" class="form-control" id="inscricao-municipal" name="inscricao-municipal">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="cnae-principal">CNAE Principal</label>
                                    <input type="text" class="form-control" id="cnae-principal" name="cnae-principal">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="cnae-secundario">CNAE Secundário</label>
                                    <input type="text" class="form-control" id="cnae-secundario" name="cnae-secundario">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="regime-tributacao">Regime de Tributação</label>
                                    <input type="text" class="form-control" id="regime-tributacao" name="regime-tributacao">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="valor-honorarios">Valor dos Honorários</label>
                                    <input type="text" class="form-control" id="valor-honorarios" name="valor-honorarios">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="vencimento-honorarios">Vencimento dos Honorários</label>
                                    <input type="text" class="form-control" id="vencimento-honorarios" name="vencimento-honorarios">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="vencimento-procuracao-caixa">Vencimento da Procuração Caixa</label>
                                    <input type="text" class="form-control" id="vencimento-procuracao-caixa" name="vencimento-procuracao-caixa">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="vencimento-procuracao-rfb">Vencimento da Procuração RFB</label>
                                    <input type="text" class="form-control" id="vencimento-procuracao-rfb" name="vencimento-procuracao-rfb">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="certificado-digital">Certificado Digital</label>
                                    <input type="text" class="form-control" id="certificado-digital" name="certificado-digital">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="senha-web">Senha da Web</label>
                                    <input type="text" class="form-control" id="senha-web" name="senha-web">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="senha-fazenda">Senha da Fazenda</label>
                                    <input type="text" class="form-control" id="senha-fazenda" name="senha-fazenda">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="tipo-empresa">Tipo da Empresa</label>
                                    <input type="text" class="form-control" id="tipo-empresa" name="tipo-empresa">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="contrato">Contrato</label>
                                    <input type="text" class="form-control" id="contrato" name="contrato">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="vencimento-contrato">Vencimento do Contrato</label>
                                    <input type="text" class="form-control" id="vencimento-contrato" name="vencimento-contrato">
                                </div>
                            </fieldset>

                            <fieldset class="fieldset-endereco">
                                <div class="form-group">
                                    <label class="control-label" for="logradouro">Logradouro</label>
                                    <input type="text" class="form-control" id="logradouro" name="logradouro">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="numero">Número</label>
                                    <input type="text" class="form-control" id="numero" name="numero">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="complemento">Complemento</label>
                                    <input type="text" class="form-control" id="complemento" name="complemento">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="municipio">Município</label>
                                    <input type="text" class="form-control" id="municipio" name="municipio">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="cep">CEP</label>
                                    <input type="text" class="form-control" id="cep" name="cep">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="estado">Estado</label>
                                    <input type="text" class="form-control" id="estado" name="estado">
                                </div>

                            </fieldset>

                            <fieldset class="fieldset-usuario">
                                <div class="form-group">
                                    <label class="control-label" for="email">Email</label>
                                    <input type="text" class="form-control" id="email" name="email">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="login">Login</label>
                                    <input type="text" class="form-control" id="login" name="login">
                                </div>

                                <div class="form-group">
                                    <label class="control-label" for="senha">Senha</label>
                                    <input type="text" class="form-control" id="senha" name="senha">
                                </div>
                            </fieldset>

                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
                <!-- /.row -->
</div>