<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle("Contjet - Gestão") ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        
        ?>

    </head>
    <body>
        <div id="wrapper">
            <div id="page-wrapper">
                <?php echo $this->content; ?>
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
