<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle("Contjet - Gestão") ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php /*echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/jquery.ui.css'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/demo-style.css'))
                        ->prependStylesheet($this->basePath('font-awesome-4.1.0/css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('css/sb-admin.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/morris.css'))
                        ->prependStylesheet($this->basePath('css/owl.carousel.css'))
                        ->prependStylesheet($this->basePath('css/owl.theme.css'))
                        ->prependStylesheet($this->basePath('css/owl.transitions.css'));
                
                
                 echo $this->headScript()
            ->prependFile($this->basePath('js/jquery.cycle.all.js'))
            ->prependFile($this->basePath('js/plugins/morris/raphael.min.js'))
            ->prependFile($this->basePath('js/plugins/morris/morris.min.js'))
            ->prependFile($this->basePath('js/plugins/morris/morris-data.js'))
            ->prependFile($this->basePath('js/modernizr.js'))
            ->prependFile($this->basePath('js/owl.carousel.min.js'))
            ->prependFile($this->basePath('js/jquery.eislideshow.js'))
            ->prependFile($this->basePath('js/jquery.easing.1.3.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/maskedInput.js'))
            ->prependFile($this->basePath('js/main.js'))
            ->prependFile($this->basePath('js/jquery.ui.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))*/ ; ?>
            
        <link href="<?php echo $this->basePath()?>/libs/jqueryui/ui-lightness/jquery-ui-1.10.4.custom.min.css" rel="stylesheet" />
        <link href="<?php echo $this->basePath()?>/libs/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <link href="<?php echo $this->basePath()?>/libs/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
        <link href="<?php echo $this->basePath()?>/libs/fontello/css/fontello.css" rel="stylesheet" />
        <link href="<?php echo $this->basePath()?>/libs/animate-css/animate.min.css" rel="stylesheet" />
        <link href="<?php echo $this->basePath()?>/libs/nifty-modal/css/component.css" rel="stylesheet" />
        <link href="<?php echo $this->basePath()?>/libs/magnific-popup/magnific-popup.css" rel="stylesheet" /> 
        <link href="<?php echo $this->basePath()?>/libs/ios7-switch/ios7-switch.css" rel="stylesheet" /> 
        <link href="<?php echo $this->basePath()?>/libs/pace/pace.css" rel="stylesheet" />
        <link href="<?php echo $this->basePath()?>/libs/sortable/sortable-theme-bootstrap.css" rel="stylesheet" />
        <link href="<?php echo $this->basePath()?>/libs/bootstrap-datepicker/css/datepicker.css" rel="stylesheet" />
        <link href="<?php echo $this->basePath()?>/libs/jquery-icheck/skins/all.css" rel="stylesheet" />
        <!-- Code Highlighter for Demo -->
        <link href="<?php echo $this->basePath()?>/libs/prettify/github.css" rel="stylesheet" />
        
        <!-- Extra CSS Libraries Start -->
        <link href="<?php echo $this->basePath()?>/libs/rickshaw/rickshaw.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath()?>/libs/morrischart/morris.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath()?>/libs/jquery-jvectormap/css/jquery-jvectormap-1.2.2.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath()?>/libs/jquery-clock/clock.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath()?>/libs/bootstrap-calendar/css/bic_calendar.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath()?>/libs/sortable/sortable-theme-bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath()?>/libs/jquery-weather/simpleweather.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath()?>/libs/bootstrap-xeditable/css/bootstrap-editable.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath()?>/css/style.css" rel="stylesheet" type="text/css" />
        <!-- Extra CSS Libraries End -->
        <link href="<?php echo $this->basePath()?>/css/style-responsive.css" rel="stylesheet" />

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <link rel="shortcut icon" href="<?php echo $this->basePath()?>/img/favicon.ico">
        <link rel="apple-touch-icon" href="<?php echo $this->basePath()?>/img/apple-touch-icon.png" />
        <link rel="apple-touch-icon" sizes="57x57" href="<?php echo $this->basePath()?>/img/apple-touch-icon-57x57.png" />
        <link rel="apple-touch-icon" sizes="72x72" href="<?php echo $this->basePath()?>/img/apple-touch-icon-72x72.png" />
        <link rel="apple-touch-icon" sizes="76x76" href="<?php echo $this->basePath()?>/img/apple-touch-icon-76x76.png" />
        <link rel="apple-touch-icon" sizes="114x114" href="<?php echo $this->basePath()?>/img/apple-touch-icon-114x114.png" />
        <link rel="apple-touch-icon" sizes="120x120" href="<?php echo $this->basePath()?>/img/apple-touch-icon-120x120.png" />
        <link rel="apple-touch-icon" sizes="144x144" href="<?php echo $this->basePath()?>/img/apple-touch-icon-144x144.png" />
        <link rel="apple-touch-icon" sizes="152x152" href="<?php echo $this->basePath()?>/img/apple-touch-icon-152x152.png" />
       

    </head>

    <body class="fixed-left">
        <!-- Modal Start -->
        	<!-- Modal Task Progress -->	
		
<!-- Begin page -->
<div id="wrapper">
		
<!-- Top Bar Start -->
<div class="topbar">
    <div class="topbar-left">
        <div class="logo">
            <h1><a href="javascript:void(0)"><img src="<?php echo $this->basePath()?>/img/logo2.png" alt="Logo"></a></h1>
        </div>
        <button class="button-menu-mobile open-left">
        <i class="fa fa-bars"></i>
        </button>
    </div>
    <!-- Button mobile view to collapse sidebar menu -->
    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-collapse2">
                
                
                <ul class="nav navbar-nav navbar-right top-navbar">
                    <?php  /*
                    <li class="dropdown iconify hide-phone">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-globe"></i><span class="label label-danger absolute">4</span></a>
                        <ul class="dropdown-menu dropdown-message">
                            <li class="dropdown-header notif-header"><i class="icon-bell-2"></i> New Notifications<a class="pull-right" href="#"><i class="fa fa-cog"></i></a></li>
                            <li class="unread">
                                <a href="#">
                                    <p><strong>John Doe</strong> Uploaded a photo <strong>&#34;DSC000254.jpg&#34;</strong>
                                        <br /><i>2 minutes ago</i>
                                    </p>
                                </a>
                            </li>
                            <li class="unread">
                                <a href="#">
                                    <p><strong>John Doe</strong> Created an photo album  <strong>&#34;Fappening&#34;</strong>
                                        <br /><i>8 minutes ago</i>
                                    </p>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <p><strong>John Malkovich</strong> Added 3 products
                                        <br /><i>3 hours ago</i>
                                    </p>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <p><strong>Sonata Arctica</strong> Send you a message <strong>&#34;Lorem ipsum dolor...&#34;</strong>
                                        <br /><i>12 hours ago</i>
                                    </p>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <p><strong>Johnny Depp</strong> Updated his avatar
                                        <br /><i>Yesterday</i>
                                    </p>
                                </a>
                            </li>
                            <li class="dropdown-footer">
                                <div class="btn-group btn-group-justified">
                                    <div class="btn-group">
                                        <a href="#" class="btn btn-sm btn-primary"><i class="icon-ccw-1"></i> Refresh</a>
                                    </div>
                                    <div class="btn-group">
                                        <a href="#" class="btn btn-sm btn-danger"><i class="icon-trash-3"></i> Clear All</a>
                                    </div>
                                    <div class="btn-group">
                                        <a href="#" class="btn btn-sm btn-success">See All <i class="icon-right-open-2"></i></a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown iconify hide-phone">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i><span class="label label-danger absolute">3</span></a>
                        <ul class="dropdown-menu dropdown-message">
                            <li class="dropdown-header notif-header"><i class="icon-mail-2"></i> New Messages</li>
                            <li class="unread">
                                <a href="#" class="clearfix">
                                    <img src="images/users/chat/2.jpg" class="xs-avatar ava-dropdown" alt="Avatar">
                                    <strong>John Doe</strong><i class="pull-right msg-time">5 minutes ago</i><br />
                                    <p>Duis autem vel eum iriure dolor in hendrerit ...</p>
                                </a>
                            </li>
                            <li class="unread">
                                <a href="#" class="clearfix">
                                    <img src="images/users/chat/1.jpg" class="xs-avatar ava-dropdown" alt="Avatar">
                                    <strong>Sandra Kraken</strong><i class="pull-right msg-time">22 minutes ago</i><br />
                                    <p>Duis autem vel eum iriure dolor in hendrerit ...</p>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="clearfix">
                                    <img src="images/users/chat/3.jpg" class="xs-avatar ava-dropdown" alt="Avatar">
                                    <strong>Zoey Lombardo</strong><i class="pull-right msg-time">41 minutes ago</i><br />
                                    <p>Duis autem vel eum iriure dolor in hendrerit ...</p>
                                </a>
                            </li>
                            <li class="dropdown-footer"><div class=""><a href="#" class="btn btn-sm btn-block btn-primary"><i class="fa fa-share"></i> See all messages</a></div></li>
                        </ul>
                    </li>
                     */ ?>
                    <li class="dropdown iconify hide-phone"><a href="#" onclick="javascript:toggle_fullscreen()"><i class="icon-resize-full-2"></i></a></li>
                    <li class="dropdown topbar-profile">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=ucfirst($_SESSION['user']['nome'])?>  &nbsp;<i class="fa fa-caret-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="javascript:void(0)">Alterar Senha</a></li>
                            <li><a href="<?php echo $this->basePath()?>/logout"><i class="icon-logout-1"></i> Sair</a></li>
                        </ul>
                    </li>
                    
                </ul>
               
                
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>
<!-- Top Bar End -->
		    <!-- Left Sidebar Start -->
        <div class="left side-menu">
            <div class="sidebar-inner slimscrollleft">
                
                <!--- Divider -->
                <div class="clearfix"></div>
                <hr class="divider" />
                <div class="clearfix"></div>
                <!--- Divider -->
                <div id="sidebar-menu">
                    <ul>
                        <li class='has_sub'>
                            <a href='javascript:void(0);'>
                                <i class='icon-home-3'></i>
                                <span>Dashboard</span>
                                <span class="pull-right">
                                    <i class="fa fa-angle-down"></i>
                                </span>
                            </a>
                            <ul>
                                <li>
                                    <a href='<?php echo $this->basePath()?>/' class='<?= $controller == 'Index' && $action == 'index' ? 'active' : ''?>'>
                                        <span>Dashboard</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class='has_sub'>
                            <a href='javascript:void(0);'>
                                <i class='fa fa-building-o'></i>
                                <span>Empresas</span>
                                <span class="pull-right">
                                    <i class="fa fa-angle-down"></i>
                                </span>
                            </a>
                            <ul>
                                <li>
                                    <a href='<?php echo $this->basePath()?>/empresa/cadastrar' class='<?= $controller == 'Empresa' && $action == 'cadastrar' ? 'active' : ''?>'>
                                        <span>Cadastrar Empresa</span>
                                    </a>
                                </li>
                                <li>
                                    <a href='<?php echo $this->basePath()?>/empresa/listar' class='<?= $controller == 'Empresa' && $action == 'index' ? 'active' : ''?>'>
                                        <span>Listar Empresas</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class='has_sub'>
                            <a href='javascript:void(0);'>
                                <i class='icon-adult'></i>
                                <span>Funcionários</span>
                                <span class="pull-right">
                                <i class="fa fa-angle-down"></i>
                                </span>
                            </a>
                            <ul>
                                <li>
                                    <a href='<?php echo $this->basePath()?>/funcionario/cadastrar' class='<?= $controller == 'Funcionario' && $action == 'cadastrar' ? 'active' : ''?>'>
                                        <span>Cadastrar Funcionário</span>
                                    </a>
                                </li>
                                <li>
                                    <a href='<?php echo $this->basePath()?>/funcionario/listar' class='<?= $controller == 'Funcionario' && $action == 'index' ? 'active' : ''?>'>
                                        <span>Listar Funcionários</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class='has_sub'>
                            <a href='javascript:void(0);'>
                                <i class='fa fa-sitemap'></i>
                                <span>Departamentos</span>
                                <span class="pull-right">
                                    <i class="fa fa-angle-down"></i>
                                </span>
                            </a>
                            <ul>
                                <li>
                                    <a href='<?php echo $this->basePath()?>/departamento/cadastrar' class='<?= $controller == 'Departamento' && $action == 'cadastrar' ? 'active' : ''?>'>
                                        <span>Cadastrar Departamentos</span>
                                    </a>
                                </li>
                                <li>
                                    <a href='<?php echo $this->basePath()?>/departamento/listar' class='<?= $controller == 'Departamento' && $action == 'index' ? 'active' : ''?>'>
                                        <span>Listar Departamentos</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class='has_sub'>
                            <a href='javascript:void(0);'>
                                <i class='icon-tools'></i>
                                <span>Ferramentas</span>
                                <span class="pull-right">
                                    <i class="fa fa-angle-down"></i>
                                </span>
                            </a>
                            <ul>
                                <li>
                                    <a href='<?php echo $this->basePath()?>/download/nfe'>
                                        <span>Download NFS-e</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class='has_sub'><a href='javascript:void(0);'><i class='icon-chart-pie-1'></i><span>Relatórios</span> <span class="pull-right"><i class="fa fa-angle-down"></i></span></a><ul><li><a href='<?php echo $this->basePath()?>/charts'><span>Relatórios A</span></a></li><li><a href='buttons.html'><span>Relatórios B</span></a></li></ul></li>
                    </ul>                    
                <div class="clearfix"></div>
                </div>
            <div class="clearfix"></div>
            
        </div>
        </div>
    <!-- Right Sidebar End -->		
		<!-- Start right content -->
        <div class="content-page">
			 
                <?php echo $this->content; ?>
            
            <footer>
                <p>&copy; <?php echo date('Y') ?> Contjet Contabilidade. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>

        </div>
		<!-- End right content -->

	</div>

	<!-- End of page -->
		<!-- the overlay modal element -->
	<div class="md-overlay"></div>
	<!-- End of eoverlay modal -->
	<script>
		var resizefunc = [];
	</script>
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script src="<?php echo $this->basePath()?>/libs/jquery/jquery-1.11.1.min.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/bootstrap/js/bootstrap.min.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/jqueryui/jquery-ui-1.10.4.custom.min.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/jquery-ui-touch/jquery.ui.touch-punch.min.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/jquery-detectmobile/detect.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/jquery-animate-numbers/jquery.animateNumbers.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/ios7-switch/ios7.switch.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/fastclick/fastclick.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/jquery-blockui/jquery.blockUI.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/bootstrap-bootbox/bootbox.min.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/jquery-slimscroll/jquery.slimscroll.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/jquery-sparkline/jquery-sparkline.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/nifty-modal/js/classie.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/nifty-modal/js/modalEffects.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/sortable/sortable.min.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/bootstrap-fileinput/bootstrap.file-input.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/bootstrap-select/bootstrap-select.min.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/bootstrap-select2/select2.min.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/magnific-popup/jquery.magnific-popup.min.js"></script> 
	<script src="<?php echo $this->basePath()?>/libs/pace/pace.min.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/jquery-icheck/icheck.min.js"></script>

	<!-- Demo Specific JS Libraries -->
	<script src="<?php echo $this->basePath()?>/libs/prettify/prettify.js"></script>

	<script src="<?php echo $this->basePath()?>/js/init.js"></script>
	<!-- Page Specific JS Libraries -->
	<script src="<?php echo $this->basePath()?>/libs/d3/d3.v3.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/rickshaw/rickshaw.min.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/raphael/raphael-min.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/morrischart/morris.min.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/jquery-knob/jquery.knob.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/jquery-jvectormap/js/jquery-jvectormap-1.2.2.min.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/jquery-jvectormap/js/jquery-jvectormap-us-aea-en.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/jquery-clock/clock.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/jquery-easypiechart/jquery.easypiechart.min.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/jquery-weather/jquery.simpleWeather-2.6.min.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/bootstrap-xeditable/js/bootstrap-editable.min.js"></script>
	<script src="<?php echo $this->basePath()?>/libs/bootstrap-calendar/js/bic_calendar.min.js"></script>
	<script src="<?php echo $this->basePath()?>/js/apps/todo.js"></script>
	<script src="<?php echo $this->basePath()?>/js/apps/notes.js"></script>
	<script src="<?php echo $this->basePath()?>/js/pages/index.js"></script>
	
	</body>
</html>
        
        
        
     <?php
     
     /*
        
        <div id="wrapper">
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="javascript:void(0)">Contjet Admin</a>
                </div>
                <!-- Top Menu Items -->
                <ul class="nav navbar-right top-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <?=$_SESSION['user']['nome']?> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="<?php echo $this->basePath()?>/logout"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav side-nav">
                        <li>
                            <a href="<?php echo $this->basePath()?>/listar"><i class="fa fa-fw fa-table"></i> Listar Empresas</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->basePath()?>/cadastrar"><i class="fa fa-fw fa-edit"></i> Cadastrar Empresas</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->basePath()?>/charts"><i class="fa fa-fw fa-bar-chart-o"></i> Relatórios</a>
                        </li>
                         <li>
                            <a href="<?php echo $this->basePath()?>/download/nfe"><i class="fa fa-fw fa-bar-chart-o"></i> Download Notas Fiscais Eletrônicas</a>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </nav>
            <div id="page-wrapper">
                <?php echo $this->content; ?>
            </div>
                <footer>
                    <p>&copy; 2015 - <?php echo date('Y') ?> by Coffee Digital Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
                </footer>
        </div>
        
    */
    ?>
    
        <?php echo $this->inlineScript() ?>
    </body>
</html>
