<div class="container-fluid">
  <!-- Modal -->
        <div class="container">
          <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">
            
              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header" style="padding:35px 50px;">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4><span class="glyphicon glyphicon-lock"></span> Login</h4>
                </div>
                <div class="modal-body" style="padding:40px 50px;">
                  <form role="form" action="<?php echo $this->basePath() ?>/" method="post"> 
                    <div class="form-group">
                      <label for="usrname"><span class="glyphicon glyphicon-user"></span> Login</label>
                      <input type="text" class="form-control" id="usrname" name="login" placeholder="Digite seu login">
                    </div>
                    <div class="form-group">
                      <label for="psw"><span class="glyphicon glyphicon-eye-open"></span> Senha</label>
                      <input type="text" class="form-control" id="psw" name="password" placeholder="Digite sua senha">
                    </div>
                    <div class="checkbox">
                      <label><input type="checkbox" value="" checked>Lembrar login</label>
                    </div>
                      <button type="submit" class="btn btn-success btn-block"><span class="glyphicon glyphicon-off"></span> Login</button>
                  </form>
                </div>
                <div class="modal-footer">
                  <button type="submit" class="btn btn-danger btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
                  <p>Nao esta cadastrado? <a href="#">Cadastre-se</a></p>
                  <p>Esqueceu sua <a href="#">Senha?</a></p>
                </div>
              </div>     
            </div>
          </div> 
        </div>
          <!-- Modal -->
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-6">
            <h1 class="page-header">
                <img src="/ierp/public/img/logo.png" />
            </h1>
           
        </div>
        <div class="col-lg-6">
            <h1 class="page-header">
                <img src="/ierp/public/img/logo.png" />
            </h1>
           
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <h1 class="page-header">
                <img src="/ierp/public/img/logo.png" />
            </h1>
           
        </div>
        <div class="col-lg-6">
            <h1 class="page-header">
                <img src="/ierp/public/img/logo.png" />
            </h1>
           
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <h1 class="page-header">
                <img src="/ierp/public/img/logo.png" />
            </h1>
           
        </div>
        <div class="col-lg-6">
            <h1 class="page-header">
                <img src="/ierp/public/img/logo.png" />
            </h1>
           
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <h1 class="page-header">
                <img src="/ierp/public/img/logo.png" />
            </h1>
           
        </div>
        <div class="col-lg-6">
            <h1 class="page-header">
                <img src="/ierp/public/img/logo.png" />
            </h1>
           
        </div>
    </div>
</div>
