<link href="http://contjet.koding.io/ierp/public/libs/jqueryui/ui-lightness/jquery-ui-1.10.4.custom.min.css" rel="stylesheet" />
<link href="http://contjet.koding.io/ierp/public/libs/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<link href="http://contjet.koding.io/ierp/public/libs/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
<link href="http://contjet.koding.io/ierp/public/libs/fontello/css/fontello.css" rel="stylesheet" />
<link href="http://contjet.koding.io/ierp/public/libs/animate-css/animate.min.css" rel="stylesheet" />
<link href="http://contjet.koding.io/ierp/public/libs/nifty-modal/css/component.css" rel="stylesheet" />
<link href="http://contjet.koding.io/ierp/public/libs/magnific-popup/magnific-popup.css" rel="stylesheet" /> 
<link href="http://contjet.koding.io/ierp/public/libs/ios7-switch/ios7-switch.css" rel="stylesheet" /> 
<link href="http://contjet.koding.io/ierp/public/libs/pace/pace.css" rel="stylesheet" />
<link href="http://contjet.koding.io/ierp/public/libs/sortable/sortable-theme-bootstrap.css" rel="stylesheet" />
<link href="http://contjet.koding.io/ierp/public/libs/bootstrap-datepicker/css/datepicker.css" rel="stylesheet" />
<link href="http://contjet.koding.io/ierp/public/libs/jquery-icheck/skins/all.css" rel="stylesheet" />
<!-- Code Highlighter for Demo -->
<link href="http://contjet.koding.io/ierp/public/libs/prettify/github.css" rel="stylesheet" />

<!-- Extra CSS Libraries Start -->
<link href="http://contjet.koding.io/ierp/public/css/style.css" rel="stylesheet" type="text/css" />
<!-- Extra CSS Libraries End -->
<link href="http://contjet.koding.io/ierp/public/css/style-responsive.css" rel="stylesheet" />

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->

<link rel="shortcut icon" href="http://contjet.koding.io/ierp/public/img/favicon.ico">
<link rel="apple-touch-icon" href="http://contjet.koding.io/ierp/public/img/apple-touch-icon.png" />
<link rel="apple-touch-icon" sizes="57x57" href="http://contjet.koding.io/ierp/public/img/apple-touch-icon-57x57.png" />
<link rel="apple-touch-icon" sizes="72x72" href="http://contjet.koding.io/ierp/public/img/apple-touch-icon-72x72.png" />
<link rel="apple-touch-icon" sizes="76x76" href="http://contjet.koding.io/ierp/public/img/apple-touch-icon-76x76.png" />
<link rel="apple-touch-icon" sizes="114x114" href="http://contjet.koding.io/ierp/public/img/apple-touch-icon-114x114.png" />
<link rel="apple-touch-icon" sizes="120x120" href="http://contjet.koding.io/ierp/public/img/apple-touch-icon-120x120.png" />
<link rel="apple-touch-icon" sizes="144x144" href="http://contjet.koding.io/ierp/public/img/apple-touch-icon-144x144.png" />
<link rel="apple-touch-icon" sizes="152x152" href="http://contjet.koding.io/ierp/public/img/apple-touch-icon-152x152.png" />



	
	<!-- Begin page -->
	<div class="container">
		<div class="full-content-center">
			<p class="text-center"><a href="javascript:void(0)"><img src="http://contjet.koding.io/ierp/public/img/logo.png" height="120" alt="Logo"></a></p>
			<div class="login-wrap animated flipInX">
				<div class="login-block">
					<form role="form" action="<?php echo $this->basePath() ?>/" method="post" id="form-login">
						<div class="form-group login-input">
						<i class="fa fa-user overlay"></i>
						<input type="text" name="login" class="form-control text-input" placeholder="Usuário">
						</div>
						<div class="form-group login-input">
						<i class="fa fa-key overlay"></i>
						<input type="password" name="password" class="form-control text-input" placeholder="********">
						</div>
						
						<div class="row">
							<div class="col-sm-6">
							<button type="submit" class="btn btn-success btn-block">Acessar</button>
							</div>
							<div class="col-sm-6">
							<a href="javascript:void(0)" class="btn btn-default btn-block">Registrar</a>
							</div>
						</div>
					</form>
				</div>
			</div>
			
		</div>
	</div>
	<!-- the overlay modal element -->
	<div class="md-overlay"></div>
	<!-- End of eoverlay modal -->
	<script>
		var resizefunc = [];
	</script>
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script src="http://contjet.koding.io/ierp/public/libs/jquery/jquery-1.11.1.min.js"></script>
	<script src="http://contjet.koding.io/ierp/public/libs/bootstrap/js/bootstrap.min.js"></script>
	<script src="http://contjet.koding.io/ierp/public/libs/jqueryui/jquery-ui-1.10.4.custom.min.js"></script>
	<script src="http://contjet.koding.io/ierp/public/libs/jquery-ui-touch/jquery.ui.touch-punch.min.js"></script>
	<script src="http://contjet.koding.io/ierp/public/libs/jquery-detectmobile/detect.js"></script>
	<script src="http://contjet.koding.io/ierp/public/libs/jquery-animate-numbers/jquery.animateNumbers.js"></script>
	<script src="http://contjet.koding.io/ierp/public/libs/ios7-switch/ios7.switch.js"></script>
	<script src="http://contjet.koding.io/ierp/public/libs/fastclick/fastclick.js"></script>
	<script src="http://contjet.koding.io/ierp/public/libs/jquery-blockui/jquery.blockUI.js"></script>
	<script src="http://contjet.koding.io/ierp/public/libs/bootstrap-bootbox/bootbox.min.js"></script>
	<script src="http://contjet.koding.io/ierp/public/libs/jquery-slimscroll/jquery.slimscroll.js"></script>
	<script src="http://contjet.koding.io/ierp/public/libs/jquery-sparkline/jquery-sparkline.js"></script>
	<script src="http://contjet.koding.io/ierp/public/libs/nifty-modal/js/classie.js"></script>
	<script src="http://contjet.koding.io/ierp/public/libs/nifty-modal/js/modalEffects.js"></script>
	<script src="http://contjet.koding.io/ierp/public/libs/sortable/sortable.min.js"></script>
	<script src="http://contjet.koding.io/ierp/public/libs/bootstrap-fileinput/bootstrap.file-input.js"></script>
	<script src="http://contjet.koding.io/ierp/public/libs/bootstrap-select/bootstrap-select.min.js"></script>
	<script src="http://contjet.koding.io/ierp/public/libs/bootstrap-select2/select2.min.js"></script>
	<script src="http://contjet.koding.io/ierp/public/libs/magnific-popup/jquery.magnific-popup.min.js"></script> 
	<script src="http://contjet.koding.io/ierp/public/libs/pace/pace.min.js"></script>
	<script src="http://contjet.koding.io/ierp/public/libs/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
	<script src="http://contjet.koding.io/ierp/public/libs/jquery-icheck/icheck.min.js"></script>

	<!-- Demo Specific JS Libraries -->
	<script src="http://contjet.koding.io/ierp/public/libs/prettify/prettify.js"></script>

	<script src="http://contjet.koding.io/ierp/public/js/init.js"></script>