<div class="container">
  <!-- Modal -->
  <div class="modal fade " id="confirm" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
          <div class="modal-body">
                Voce tem certeza que deseja excluir essa empresa?
          </div>
        <div class="modal-footer">
          <button class="btn btn-danger btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
          <button class="btn btn-success btn-default pull-right" data-dismiss="modal"><span class="glyphicon glyphicon-on"></span> Ok</button>
        </div>
      </div>     
    </div>
  </div> 
</div>
